version: "3.8"

services:
  base:
    image: tschaffter/debian:base-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.base
      args:
        version: ${version}
    hostname: base
    extra_hosts:
      - "base:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    command: /bin/bash

  user:
    image: tschaffter/debian:user-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.user
      args:
        user: ${user}
        version: ${version}
    hostname: user
    extra_hosts:
      - "user:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  docker:
    image: tschaffter/debian:docker-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.docker
      args:
        user: ${user}
        version: ${version}
    hostname: docker
    extra_hosts:
      - "docker:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/bash

  python:
    image: tschaffter/debian:python-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.python
      args:
        user: ${user}
        version: ${version}
    hostname: python
    extra_hosts:
      - "python:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  conda:
    image: tschaffter/debian:conda-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.conda
      args:
        user: ${user}
        version: ${version}
    hostname: conda
    extra_hosts:
      - "conda:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  synapse:
    image: tschaffter/debian:synapse-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.synapse
      args:
        version: ${version}
    hostname: synapse
    extra_hosts:
      - "synapse:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  node:
    image: tschaffter/debian:node-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.node
      args:
        version: ${version}
    hostname: node
    extra_hosts:
      - "node:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - "443:443"
    #   - "9000:9000"
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  cxx:
    image: tschaffter/debian:cxx-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.cxx
      args:
        version: ${version}
    hostname: cxx
    extra_hosts:
      - "cxx:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

  esp:
    image: tschaffter/debian:esp-${version}
    build:
      context: ./docker
      dockerfile: Dockerfile.esp
      args:
        version: ${version}
    hostname: esp
    extra_hosts:
      - "esp:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    command: /bin/bash

volumes:
  home-persist:
