version: "3.8"

services:
  base:
    image: tschaffter/debian:base-${version}
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        version: ${version}
    hostname: base
    restart: unless-stopped
    extra_hosts:
      - "base:127.0.0.1"
    network_mode: host
    command: /bin/bash

  user:
    image: tschaffter/debian:user-${version}
    build:
      context: .
      dockerfile: Dockerfile.user
      args:
        user: ${user}
        version: ${version}
    hostname: user
    restart: unless-stopped
    # environment:
    #   TERM: "xterm-color"
    extra_hosts:
      - "user:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  docker:
    image: tschaffter/debian:docker-${version}
    build:
      context: .
      dockerfile: Dockerfile.docker
      args:
        user: ${user}
        version: ${version}
    hostname: docker
    restart: unless-stopped
    extra_hosts:
      - "docker:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "22"
    command: >
      bash -c "sudo chown root:docker /var/run/docker.sock
      && /bin/bash"

  python:
    image: tschaffter/debian:python-${version}
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        user: ${user}
        version: ${version}
    hostname: python
    restart: unless-stopped
    extra_hosts:
      - "python:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  synapse:
    image: tschaffter/debian:synapse-${version}
    build:
      context: .
      dockerfile: Dockerfile.synapse
      args:
        version: ${version}
    hostname: synapse
    restart: unless-stopped
    extra_hosts:
      - "synapse:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  node:
    image: tschaffter/debian:node-${version}
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        version: ${version}
    hostname: node
    restart: unless-stopped
    extra_hosts:
      - "node:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  esp:
    image: tschaffter/debian:esp-${version}
    build:
      context: .
      dockerfile: Dockerfile.esp
      args:
        version: ${version}
    hostname: esp
    restart: unless-stopped
    extra_hosts:
      - "esp:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

volumes:
  home-persist:
