FROM debian:buster-20200607-slim

LABEL maintainer="thomas.schaffter@gmail.com"

ARG version
RUN test -n "${version}"

ENV version=${version}
LABEL version=${version}

# Install dependencies
# hadolint ignore=DL3008
RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
    apt-transport-https \
    ca-certificates \
    wget \
    && update-ca-certificates \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
