version: "3.8"

services:
  user:
    image: tschaffter/debian:user-${version}
    hostname: user
    restart: unless-stopped
    # environment:
    #   TERM: "xterm-color"
    extra_hosts:
      - "user:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  docker:
    image: tschaffter/debian:docker-${version}
    hostname: docker
    restart: unless-stopped
    extra_hosts:
      - "docker:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "22"
    command: >
      bash -c "sudo chown root:docker /var/run/docker.sock
      && /bin/bash"

  python:
    image: tschaffter/debian:python-latest
    hostname: python
    restart: unless-stopped
    extra_hosts:
      - "python:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

  synapse:
    image: tschaffter/debian:synapse-latest
    hostname: synapse
    restart: unless-stopped
    extra_hosts:
      - "synapse:127.0.0.1"
    network_mode: host
    volumes:
      - home-persist:/home/tschaffter/persist
    expose:
      - "22"
    command: /bin/bash

volumes:
  home-persist:
