FROM debian:buster-20200607-slim

LABEL maintainer="thomas.schaffter@gmail.com"

# Install dependencies
# hadolint ignore=DL3008
RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
    apt-transport-https \
    ca-certificates \
    wget \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp