FROM tschaffter/debian:python-latest

# Create synapse conda environment
RUN conda create --name synapse python=3.8 \
    && conda run --name synapse pip install \
    synapseclient==2.1.1 \
    challengeutils==2.2.0 \
    pandas==1.0.5

# Activate synapse environment when logging in
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN echo "source activate synapse" | tee -a ~/.bashrc
